openapi: 1.0.0
info:
  title: Announces Immpobiliers - API
  description: |-
    Announces TP
  contact:
    email: noemail@exemple.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
- url: http://localhost:8080
tags:
- name: announce
  description: Tout sur les Annonces
paths:
  /announce/:
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      example:
        code: 0
        type: type
        message: message
      xml:
        name: '##default'
  requestBodies:
    Announce:
      description: Announce object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Announce'
        application/xml:
          schema:
            $ref: '#/components/schemas/Announce'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:announces: modify announces in your account
            read:announces: read your announces
    api_key:
      type: apiKey
      name: api_key
      in: header
