openapi: 3.0.3
info:
  title: Announces Immpobiliers - API
  description: |-
    Announces TP
  contact:
    email: noemail@exemple.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
- url: http://localhost:8080
tags:
- name: announce
  description: Tout sur les Annonces
paths:
  /announces:
    get:
      tags:
      - announce
      summary: Get all announces
      description: Get all announces dans la bd
      operationId: getAllAnnounces
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Announce'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Announce'
components:
  schemas:
    Announce:
      required:
      - name
      - type
      type: object
      properties:
        name:
          type: string          
          example: AnnounceParis
        type:
          type: string
          enum:
            - Vente
            - Location
        published:
          type: boolean
          example: false
        status:
          type: string
          enum:
            - Disponible
            - Loué
            - Vendu
        description:
          type: string
        price:
          type: number
        date:
          type: date
        photos:
          type: array
        by:
          type: string
        comments:
          type: array
      xml:
        name: announce
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      example:
        code: 0
        type: type
        message: message
      xml:
        name: '##default'
  requestBodies:
    Announce:
      description: Announce object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Announce'
        application/xml:
          schema:
            $ref: '#/components/schemas/Announce'
    api_key:
      type: apiKey
      name: api_key
      in: header
